services:
  gerbil_porgy_blog:
    container_name: gerbil_porgy_blog
    image: gerbil_porgy_blog:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 45:3000
    restart: always
