services:
  gerbil_porgy_recipes:
    container_name: gerbil_porgy_recipes
    image: gerbil_porgy_recipes:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 806:3000
    restart: always
